# Generated by Django 3.1.13 on 2021-12-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeAndCert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_of_study", models.CharField(max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BA", "Bachelor"),
                            ("MI", "Minor"),
                            ("CE", "Certificate"),
                            ("MA", "Master"),
                            ("PH", "PhD"),
                        ],
                        max_length=2,
                    ),
                ),
                ("short_code", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_group_1",
                    models.CharField(
                        choices=[
                            ("DST", "Distance"),
                            ("JMP", "Jumps"),
                            ("MLT", "Multi"),
                            ("SPR", "Sprints"),
                            ("THR", "Throws"),
                        ],
                        default="DST",
                        max_length=3,
                    ),
                ),
                (
                    "event_group_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DST", "Distance"),
                            ("JMP", "Jumps"),
                            ("MLT", "Multi"),
                            ("SPR", "Sprints"),
                            ("THR", "Throws"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "year_in_school",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
                ("degrees", models.ManyToManyField(to="user_profile.DegreeAndCert")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event_group_1", "event_group_2")},
            },
        ),
    ]
